### ISSUE TITLE
publish openxml-explorer on open-vsx

### ISSUE THREAD

**Issue by goyalyashpal** [sergey-tihon/vscode-openxml-explorer#25]
hi

thanks a lot for this wonderful extension. 
do you have any plans for publishing this to open-vsx so that client applications like vscodium etc can use it too :)

**Comment by sergey-tihon** [comment]
I know nothing about open-vsx, but it is uses the same format you can open the `settings.json` and add or update the `files.associations` and add an associate with `openxml`. 

```
"files.associations": {
  "*.vsix": "openxml"
}
```

**Comment by goyalyashpal** [comment]
https://open-vsx.org

Open VSX Registry
Extensions for VS Code Compatible Editors

This is just like the https://marketplace.visualstudio.com/ Visual Studio Marketplace which is owned by Microsoft.

VSCodium (the _really_ FOSS build of ~VSCode~ Code OSS) can't legally use the MS VS marketplace

this OpenVSX serves that purpose

**Comment by goyalyashpal** [comment]
yes, i think i get it :)

![image](https://github.com/sergey-tihon/vscode-openxml-explorer/assets/19423063/09c34fd9-0f08-468e-9662-24f5ff6d6235)

**Comment by goyalyashpal** [comment]
> right click on the file and click "Explore OpenXml Package"
> _@ sergey-tihon at https://github.com/sergey-tihon/vscode-openxml-explorer/issues/6#issuecomment-818983251_

on doing that, it showed following (in the outputs tab in bottom panel):

reading here: I think i need to update the .net framework, right?

`The framework 'Microsoft.AspNetCore.App', version '6.0.0' (x64) was not found.`

<details>
<summary>Output</summary>

```
Starting server on port 20489 ...
API server started at http://0.0.0.0:20489
It was not possible to find any compatible framework version
The framework 'Microsoft.AspNetCore.App', version '6.0.0' (x64) was not found.
  - No frameworks were found.

You can resolve the problem by installing the specified framework and/or SDK.

The specified framework can be found at:
  - https://aka.ms/dotnet-core-applaunch?framework=Microsoft.AspNetCore.App&framework_version=6.0.0&arch=x64&rid=win10-x64

ExecError: Error: Command failed: dotnet Server.dll http://0.0.0.0:20489
It was not possible to find any compatible framework version
The framework 'Microsoft.AspNetCore.App', version '6.0.0' (x64) was not found.
  - No frameworks were found.

You can resolve the problem by installing the specified framework and/or SDK.

The specified framework can be found at:
  - https://aka.ms/dotnet-core-applaunch?framework=Microsoft.AspNetCore.App&framework_version=6.0.0&arch=x64&rid=win10-x64


```

</details>
